project:
  type: website
  output-dir: docs
  render: 
  - "*.qmd"
  - "!dashboard/toolkit_dashboard1.qmd"

execute:
  freeze: auto

variables:
  author_default: Greg Brooks

website:
  title: "A Prospect Dev Field Notebook"
  description: Insider notes and analysis on prospect dev, management, and research
  site-url:  https://prospectresearchtoolkit.github.io/ProspectResearchToolkit/
  open-graph: true
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    background: secondary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Field Notes"
        href: field_notes.qmd
      
  reader-mode: false
  page-footer: 
    left: " "

extensions:
  badge:
    - key: toolbadge
      color: "#9E5829"
    

format:
  html:
    page-layout: full
    respect-user-color-scheme: true
    theme: sandstone
    css: styles.css
    toc: true



